### ISSUE TITLE
aiohttp 3 broke HA

### ISSUE THREAD

**Issue by Superpiffer** [kamaradclimber/home-assistant-aur#6]
aiohttp from packages (https://www.archlinux.org/packages/community/x86_64/python-aiohttp/) broke home assistant:

```
2018-02-26 17:44:34 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/http/__init__.py", line 147, in start_server
    yield from server.start()
  File "/usr/lib/python3.6/site-packages/homeassistant/components/http/__init__.py", line 282, in start
    yield from self.app.startup()
  File "/usr/lib/python3.6/site-packages/aiohttp/web_app.py", line 249, in startup
    await self.on_startup.send(self)
  File "/usr/lib/python3.6/site-packages/aiohttp/signals.py", line 32, in send
    raise RuntimeError("Cannot send non-frozen signal.")
RuntimeError: Cannot send non-frozen signal.
```

That's because HA is not compatible yet with aiohttp3 so there's nothing we can do. For now I'm ignoring the pkg with pacman.conf but I think that you need a more reliable solution.

**Comment by kamaradclimber** [comment]
fixed upstream
